### ISSUE TITLE
Does it actually work, is it supported? 

### ISSUE THREAD

**Issue by kwikiel** [BerriAI/bettertest#2]
I've did example from the hello world based on the documentation and I've got empty response. 
<img width="1282" alt="Screenshot 2024-01-24 at 13 36 58" src="https://github.com/BerriAI/bettertest/assets/5274399/ad09bdb1-1f0f-418f-849d-258c50e57de8">

**Comment by krrishdholakia** [comment]
No this is no longer supported - apologies @kwikiel 

Added the notice to the README as well
